### ISSUE TITLE
Cannot load relationships to a Kotlin data class

### ISSUE THREAD

**Issue by martinoconnor** [neo4j/sdn-rx#102]
Given the following definition

```
@Node
data class DeviceEntity(
        @Id
        val deviceId: String,
        val phoneNumber: String,
        @Relationship(type = "LATEST_LOCATION", direction = OUTGOING)
        val location: LocationEntity?
)

@Node
data class LocationEntity(
        @Id
        @GeneratedValue
        val locationId: Long? = null,
        val latitude: Double,
        val longitude: Double,
        @Relationship(type = "PREVIOUS_LOCATION", direction = OUTGOING)
        val previousLocation: LocationEntity?
)

interface DeviceRepository: ReactiveCrudRepository<DeviceEntity, String>
```
When I invoke `deviceRepository.findById("123")` the following exception is generated
```
Caused by: org.springframework.data.mapping.MappingException: Error mapping Record<{n: {phoneNumber: "some number", deviceId: "123", DeviceEntity_LATEST_LOCATION_LocationEntity: [{__internalNeo4jId__: 3, LocationEntity_PREVIOUS_LOCATION_LocationEntity: [], latitude: 20.0, longitude: 20.0}]}}>
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.read(DefaultNeo4jConverter.java:136)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.read(DefaultNeo4jConverter.java:71)
	at org.neo4j.springframework.data.core.schema.Schema.lambda$getRequiredMappingFunctionFor$0(Schema.java:110)
	at org.neo4j.springframework.data.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:48)
	at org.neo4j.springframework.data.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:38)
	at org.neo4j.springframework.data.core.DefaultReactiveNeo4jClient$DefaultRecordFetchSpec.lambda$executeWith$2(DefaultReactiveNeo4jClient.java:240)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at org.neo4j.driver.internal.shaded.reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at org.neo4j.driver.internal.shaded.reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
	at org.neo4j.driver.internal.shaded.reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
	at org.neo4j.driver.internal.reactive.InternalRxResult.lambda$createRecordConsumer$3(InternalRxResult.java:95)
	at org.neo4j.driver.internal.handlers.pulln.BasicPullResponseHandler.onRecord(BasicPullResponseHandler.java:110)
	at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleRecordMessage(InboundMessageDispatcher.java:97)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackRecordMessage(MessageReaderV1.java:94)
	at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:65)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
	at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
	at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429)
	at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.data.mapping.MappingException: This property is not mapped to a Graph property!
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jPersistentProperty.getPropertyName(DefaultNeo4jPersistentProperty.java:146)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.extractValueOf(DefaultNeo4jConverter.java:424)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.access$000(DefaultNeo4jConverter.java:71)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter$1.getParameterValue(DefaultNeo4jConverter.java:271)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.extractInvocationArguments(ClassGeneratingEntityInstantiator.java:250)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:223)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.instantiate(DefaultNeo4jConverter.java:276)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.map(DefaultNeo4jConverter.java:244)
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.read(DefaultNeo4jConverter.java:133)
```

**Comment by martinoconnor** [comment]
Adding a no-arg constructor to `@Node` annotated classes has no effect as the primary constructor is still used by `KotlinClassGeneratingEntityInstantiator`

**Comment by meistermeier** [comment]
Thanks for reporting this. The mapping of immutable objects is not yet finished.
The data class you are defining expects to already have the relationship `location` created when the its instantiation gets called. The mapping logic can only handle non-relationship properties at the moment. Because it assumes that `location` is not a relationship it fails with this error message.
