### ISSUE TITLE
When persisting Relationship with Properties, cannot find PersistentEntity for ImmutableCollections$Map1

### ISSUE THREAD

**Issue by thePhil** [neo4j/sdn-rx#105]
**Edit**
Please check here for a test on the SDN-RX Integration test suite, that demonstrates the issue:
https://github.com/thePhil/sdn-rx/commit/f86591d4278408acdabb6570f1bdaae88fcb2a9f 

** Original Post **
Hoi,

I'm trying out the latest version of SDN-RX and I come across the following error when trying to `save()` an entity, stacktrace at the bottom:

```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.util.ImmutableCollections$Map1!
```
In case a more complete example is necessary, I'm happy to provide one.

The code I'm trying to persist looks like the following:

ChartEntity.java
```java
@Node
@Value(staticConstructor = "of")
@Builder
@With
@Slf4j
public class Chart {

    @Id
    @GeneratedValue
    private Long id;
    @Relationship("REFRESHED_FROM")
    private Map<SourceSystem, RefreshedFromSystem> refreshedFromSystem;

// hashcode, toString and equals omitted
}
```

SourceSystem.java
```java
@Value(staticConstructor = "of")
@Builder
@Node
public class SourceSystem {

    @Id
    @GeneratedValue
    private Long id;

    private SourceSystemType type;

// hashcode, toString and equals omitted
}

public enum SourceSystemType{
    SYS1;
}
```

RefreshedFromSystem.java
```java
@Value(staticConstructor = "of")
@RelationshipProperties
public class RefreshedFromSystem {

    private Instant refreshDate;
}
```

ChartRepository.java
```java
public interface ChartRepository extends Neo4jRepository<Chart, Long> {
}
```

The complete Stacktrace:
```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.util.ImmutableCollections$Map1!

	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79)
	at org.neo4j.springframework.data.repository.event.IdPopulator.populateIfNecessary(IdPopulator.java:51)
	at org.neo4j.springframework.data.repository.event.IdGeneratingBeforeBindCallback.onBeforeBind(IdGeneratingBeforeBindCallback.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279)
	at org.springframework.data.mapping.callback.EntityCallbackDiscoverer.lambda$computeCallbackInvokerFunction$2(EntityCallbackDiscoverer.java:340)
	at org.springframework.data.mapping.callback.DefaultEntityCallbacks$SimpleEntityCallbackInvoker.invokeCallback(DefaultEntityCallbacks.java:111)
	at org.springframework.data.mapping.callback.DefaultEntityCallbacks.callback(DefaultEntityCallbacks.java:88)
	at org.neo4j.springframework.data.core.Neo4jTemplate$Neo4jEvents.maybeCallBeforeBind(Neo4jTemplate.java:447)
	at org.neo4j.springframework.data.core.Neo4jTemplate.lambda$processNestedAssociations$11(Neo4jTemplate.java:351)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:382)
	at org.neo4j.springframework.data.core.Neo4jTemplate.processNestedAssociations(Neo4jTemplate.java:316)
	at org.neo4j.springframework.data.core.Neo4jTemplate.save(Neo4jTemplate.java:189)
	at org.neo4j.springframework.data.repository.support.SimpleNeo4jRepository.save(SimpleNeo4jRepository.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy112.save(Unknown Source)
```

**Comment by meistermeier** [comment]
Closed with the merge of #108.
