### ISSUE TITLE
Using self referential relationships during ctor initialization leads to an IllegalStateException

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#143]
Given `data class Person(@Id val name: String, val wasOnboardedBy: List<Person>)` or the corresponding Java class will lead to  an illegalstate exxception during traversal of the visited relationships

```
Caused by: java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1760) ~[na:na]
	at org.neo4j.springframework.data.core.mapping.DefaultNeo4jConverter.createInstanceOfRelationships(DefaultNeo4jConverter.java:411) ~[spring-data-neo4j-rx-1.0.0-beta03.jar:1.0.0-beta03]
```

See https://blog.jooq.org/2015/03/04/avoid-recursion-in-concurrenthashmap-computeifabsent/

**Comment by michael-simons** [comment]
I have a fix here https://github.com/neo4j/sdn-rx/commit/a141b0c818d96d0e70805823bf6d5f086c2e2787 but need tests to verify it.
